Dockerfile instructions:

1. From : is used to specify the base image for the current image.

   From image-name:version

2. LABEL : is used to add information to a Dockerfile.

  LABEL key1=value1 key2=value2

3. RUN : executes commands in a new layer on top of the current image and commit the result to be used in the next step.

  It can be used in two ways:
  a) RUN <command> (shell form, the command is run in a shell)
  b) RUN ["executable", "param1", "param2"] (exec form, doesn't inovke shell)

4. CMD : Is used to provide defaults for an executing container. It does not execute anything at build time, but specifies the intended command for the image.
 
 It can be used in two ways:
 a) CMD ["executable","param1","param2"] (exec form, this is the preferred form)
 b) CMD ["param1","param2"] (as default parameters to ENTRYPOINT)

5. EXPOSE : Is used to expose a container port to be mapped to an arbitary host port.

EXPOSE <port> 
EXPOSE <port>/<protocol>

6. ENV : Is used to set an environment variable to be used in the subsequent instructions in the build stage.

ENV <key>=<value>

7. ADD : Copies new files, directories or remote file URLs from <src> and adds them to the filesystem of the image at the path <dest>.

ADD [--chown=<user>:<group>] <src>... <dest>  
ADD [--chown=<user>:<group>] ["<src>",... "<dest>"]

8. COPY : Copies new files or directories from <src> and adds them to the filesystem of the container at the path <dest>.

COPY [--chown=<user>:<group>] <src>... <dest>  
COPY [--chown=<user>:<group>] ["<src>",... "<dest>"]

9. ENTRYPOINT : Allows you to configure a container that will run as an executable.

ENTRYPOINT ["executable", "param1", "param2"] (exec form, preferred)
ENTRYPOINT command param1 param2 (shell form)

10. WORKDIR : Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the Dockerfile. 

WORKDIR /path/to/workdir

11. ARG : Defines a variable that users can pass at build-time to the builder with the docker build command using the --build-arg <varname>=<value> flag. 

ARG <name>[=<default value>]

12. ONBUILD : Adds to the image a trigger instruction to be executed at a later time, when the image is used as the base for another build. The trigger will be executed in the context of the downstream build, as if it had been inserted immediately after the FROM instruction in the downstream Dockerfile.

ONBUILD [INSTRUCTION]


